[package]
name = "actix-web-example"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
actix-web = "4.11.0"
sbolt = { path = "../../../core/lib" }

[build-dependencies]
sbolt = { path = "../../../core/lib", features = ["pretty"] }

