[package]
name = "rocket-example"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sbolt = { path = "../../../core/lib" }
rocket = "0.5.1"

[build-dependencies]
sbolt = { path = "../../../core/lib", features = ["pretty"] }
