mod doc;
mod node;
mod parser;

#[cfg(test)]
mod tests;

use crate::types::result;
// The goal is not to parse and geneted a strict doc but fragments as the whole doc content is devided by diffrent type of blocks, some blocks will be evaluated
// at runtime. Also wellformed node(s) might be generated by concatenating by all blocks(static/runtime). Goal is to do as much as possible to optimize blocks to
// remove unneeded chars from static cotnent to reduce bits size and ops on str operations.
// "<div att1="a">test " => "<div att1="a">test "
// "<div att1=" => n"<div att1="
// "<div att=\"a\">test</div>" => "<div att=\"a\">test</div>"
pub(in crate::codegen) fn parse_html<'s>(raw_html: &'s str) -> result::Result<doc::HtmlDocument> {
    doc::HtmlDocument::parse(raw_html)
}
