[package]
name = "cli"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sbolt = { path = "../../core/lib" }

[build-dependencies]
sbolt = { path = "../../core/lib", features = ["pretty"] }
#sbolt = { path = "../../core/lib" }
